services:
  webponpes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asah_chabot
    ports:
      - '3000:3000'
    command: sh -c "node --env-file=.env build/index.js"
    restart: unless-stopped